services:
  hapapp:
    container_name: hapapp-development
    image: hapapp-online:development
    ports:
      - "5050:8050"
    environment:
      TLS_ENABLED: "true"
      TLS_CERT_PATH: /cert.pem
      TLS_KEY_PATH: /key.pem
    volumes:
      - ./config/development.env:/app/config/development.env:ro
      - hapapp-development-runs:/tmp/hapapp_online_runs
      - /etc/ssl/certs/ifs-brin-01.pem:/cert.pem:ro
      - /etc/ssl/private/ifs-brin-01.key:/key.pem:ro
    restart: unless-stopped

volumes:
  hapapp-development-runs:
