services:
  hapapp:
    container_name: hapapp-development
    image: hapapp-online:development
    volumes:
      - ./config/development.env:/app/.env:ro
      - hapapp-development-runs:/tmp/hapapp_online_runs
    restart: unless-stopped

volumes:
  hapapp-development-runs:
