services:
  hapapp:
    container_name: hapapp-production
    image: hapapp-online:production
    ports:
      - "5081:8050"
    environment:
      TLS_ENABLED: "true"
      TLS_CERT_PATH: /cert.pem
      TLS_KEY_PATH: /key.pem
    volumes:
      - ./config/production.env:/app/config/production.env:ro
      - hapapp-production-runs:/tmp/hapapp_online_runs
      - /etc/ssl/certs/ifs-brin-01.pem:/cert.pem:ro
      - /etc/ssl/private/ifs-brin-01.key:/key.pem:ro
    restart: unless-stopped

volumes:
  hapapp-production-runs:
