[project]
name = "hapapp-local"
version = "0.1.0"
description = "Dash interface for HapApp microhaplotype workflows"
channels = ["conda-forge", "bioconda"]
platforms = ["osx-arm64", "osx-64", "linux-64"]

[dependencies]
python = ">=3.10,<3.14"
blast = "*"
hmmer = "*"
seqkit = "*"
mmseqs2 = "*"

[pypi-dependencies]
hapapp-local = { path = ".", editable = true }
biopython = "*"
cutadapt = "*"
dash = "*"
dash-bootstrap-components = "*"
pandas = "*"
dash-uploader = ">=0.6.1, <0.7"

[tasks]
hapapp-local = "hapapp-local"
